# Maching Learning

#### This notebook will clean the data, drop any irrelevant columns, and train a model to predict the time is takes to complete each ticket.

In [3]:
import pandas as pd
import numpy as np

In [5]:
pd.set_option('display.max_columns', None)
df = pd.read_csv("jira_m2_accelerated.csv")
df

,issue_key,issue_type,priority_numeric,status,component,story_points,sprint,assignee_id,reporter_id,resolution,num_comments,num_attachments,watchers_count,time_to_resolution_hours,num_transitions,description_length,ticket_age_days,has_labels,parent_epic_id,parent_story_id,has_child_stories,has_child_subtasks,priority,created_date,updated_date,problem_statement,description,cause
0,USR-11480,Sub-task,5,Code Review,Payment Processing,3,Sprint 17,41,15,Unresolved,7,1,1,41.09,3,28,39,0,NaN,USR-10463,0,0,Highest,2025-09-19,2025-10-17,File Upload experiencing form validation failures,QA testing identified data completeness affect...,Application logic in file upload missing data ...
1,APP-11312,Story,5,Closed,API Services,5,Sprint 14,7,83,Done,5,3,1,71.18,3,37,40,1,WEB-10522,NaN,0,0,Highest,2025-09-18,2025-10-07,Password Reset showing timeout errors,Users reporting timeout errors in password res...,Frontend optimization needed for password reset
2,MOB-10305,Bug,3,In Progress,API Services,3,Sprint 6,48,40,Unresolved,5,1,4,45.39,4,27,63,1,NaN,NaN,0,0,Medium,2025-08-26,2025-09-11,Data Export showing performance slowdown,Users reporting performance slowdown in data e...,Frontend optimization needed for data export
3,WEB-11545,Epic,4,In Progress,Analytics,1,Sprint 13,91,176,Unresolved,4,1,2,25.08,2,51,9,1,NaN,NaN,1,0,High,2025-10-19,2025-10-28,Review Submission showing browser compatibility,Users reporting browser compatibility in revie...,Frontend optimization needed for review submis...
4,API-11716,Bug,5,To Do,Payment Processing,5,Sprint 8,102,61,Unresolved,3,0,1,88.71,1,44,69,0,NaN,NaN,0,0,Highest,2025-08-20,2025-09-13,Subscription Management experiencing text trun...,QA testing identified incorrect data affecting...,Application logic in subscription management m...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,USR-10277,Task,4,Code Review,API Services,3,Sprint 2,22,50,Unresolved,6,1,1,22.47,2,29,13,1,NaN,NaN,0,0,High,2025-10-15,2025-11-02,Data Export showing browser compatibility,Users reporting browser compatibility in data ...,Frontend optimization needed for data export
1996,WEB-11841,Task,3,In Progress,User Management,2,Sprint 4,25,39,Unresolved,6,3,2,104.21,1,15,62,0,NaN,NaN,0,0,Medium,2025-08-27,2025-09-20,Password Reset showing loading delays,Users reporting loading delays in password res...,Frontend optimization needed for password reset
1997,APP-10255,Task,1,Closed,Customer Portal,2,Sprint 17,79,80,Done,8,1,1,76.46,3,15,98,1,NaN,NaN,0,0,Lowest,2025-07-22,2025-07-23,Account Settings showing browser compatibility,Users reporting browser compatibility in accou...,Frontend optimization needed for account settings
1998,APP-11344,Task,2,Code Review,Payment Processing,2,Sprint 20,73,194,Unresolved,5,2,0,94.66,4,61,15,0,NaN,NaN,0,0,Low,2025-10-13,2025-10-22,Customer Profile experiencing text truncation,QA testing identified data inconsistency affec...,Application logic in customer profile missing ...
1999,MOB-11860,Story,4,In Progress,Mobile App,1,Sprint 4,69,104,Unresolved,2,0,5,83.02,1,32,92,0,APP-10048,NaN,0,0,High,2025-07-28,2025-08-13,Product Search showing timeout errors,Users reporting timeout errors in product sear...,Frontend optimization needed for product search

## Data Cleaning

In [6]:
df.drop(columns=["issue_key", "problem_statement", "description", "cause"], inplace=True)
df

,issue_type,priority_numeric,status,component,story_points,sprint,assignee_id,reporter_id,resolution,num_comments,num_attachments,watchers_count,time_to_resolution_hours,num_transitions,description_length,ticket_age_days,has_labels,parent_epic_id,parent_story_id,has_child_stories,has_child_subtasks,priority,created_date,updated_date
0,Sub-task,5,Code Review,Payment Processing,3,Sprint 17,41,15,Unresolved,7,1,1,41.09,3,28,39,0,NaN,USR-10463,0,0,Highest,2025-09-19,2025-10-17
1,Story,5,Closed,API Services,5,Sprint 14,7,83,Done,5,3,1,71.18,3,37,40,1,WEB-10522,NaN,0,0,Highest,2025-09-18,2025-10-07
2,Bug,3,In Progress,API Services,3,Sprint 6,48,40,Unresolved,5,1,4,45.39,4,27,63,1,NaN,NaN,0,0,Medium,2025-08-26,2025-09-11
3,Epic,4,In Progress,Analytics,1,Sprint 13,91,176,Unresolved,4,1,2,25.08,2,51,9,1,NaN,NaN,1,0,High,2025-10-19,2025-10-28
4,Bug,5,To Do,Payment Processing,5,Sprint 8,102,61,Unresolved,3,0,1,88.71,1,44,69,0,NaN,NaN,0,0,Highest,2025-08-20,2025-09-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Task,4,Code Review,API Services,3,Sprint 2,22,50,Unresolved,6,1,1,22.47,2,29,13,1,NaN,NaN,0,0,High,2025-10-15,2025-11-02
1996,Task,3,In Progress,User Management,2,Sprint 4,25,39,Unresolved,6,3,2,104.21,1,15,62,0,NaN,NaN,0,0,Medium,2025-08-27,2025-09-20
1997,Task,1,Closed,Customer Portal,2,Sprint 17,79,80,Done,8,1,1,76.46,3,15,98,1,NaN,NaN,0,0,Lowest,2025-07-22,2025-07-23
1998,Task,2,Code Review,Payment Processing,2,Sprint 20,73,194,Unresolved,5,2,0,94.66,4,61,15,0,NaN,NaN,0,0,Low,2025-10-13,2025-10-22
1999,Story,4,In Progress,Mobile App,1,Sprint 4,69,104,Unresolved,2,0,5,83.02,1,32,92,0,APP-10048,NaN,0,0,High,2025-07-28,2025-08-13